#!/bin/sh
case "$2,$3" in
  merge,)
    /run/current-system/sw/bin/perl -i.bak -ne 's/^/# /, s/^# #/#/ if /^Conflicts/ .. /#/; print' "$1" ;;

 ,template,)
  /run/current-system/sw/bin/perl -i.bak -pe '
    print "\n" . `git diff --cached --name-status -r`
  if /^#/ && $first++ == 0' "$1" ;;

  *) ;;
esac

#SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
#grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"
